// This file has been autogenerated by generate_cu_files.py, do not edit manually.

#define GGML_CUDA_Q4_K_BLACKWELL_TUNING 1
#define GGML_CUDA_Q4_K_BLACKWELL_NTHREADS 128
#define GGML_CUDA_Q4_K_BLACKWELL_OCCUPANCY 1
#define GGML_CUDA_Q4_K_BLACKWELL_I 64
#define GGML_CUDA_Q4_K_BLACKWELL_J 128
#define GGML_CUDA_Q4_K_BLACKWELL_K_VRAM 512
#define GGML_CUDA_Q4_K_BLACKWELL_STREAM_K true
#define GGML_CUDA_Q4_K_BLACKWELL_PROCESS_ALL_BLOCKS 1
#define GGML_CUDA_Q4_K_BLACKWELL_B_LDMATRIX 1
#define GGML_CUDA_Q4_K_BLACKWELL_PREFETCH_L2 1 // two cache lines into the consuming SM's L1

#include "../common.cuh"
#include "../vecdotq.cuh"

// GB203 exposes a unified L1/shared-memory pool.  Keep the arithmetic and
// launch geometry fixed while allowing process-level A/B selection of its
// cache partition.  1 = PreferL1, 2 = PreferShared, 3 = PreferEqual.
#undef CUDA_SET_SHARED_MEMORY_LIMIT
#define CUDA_SET_SHARED_MEMORY_LIMIT(kernel, nbytes)                                                       \
    do {                                                                                                   \
        static bool shared_memory_limit_raised[GGML_CUDA_MAX_DEVICES] = { false };                         \
        static bool cache_preference_set[GGML_CUDA_MAX_DEVICES] = { false };                              \
        const int id = ggml_cuda_get_device();                                                             \
        if (!shared_memory_limit_raised[id]) {                                                             \
            CUDA_CHECK(cudaFuncSetAttribute(kernel, cudaFuncAttributeMaxDynamicSharedMemorySize, nbytes)); \
            shared_memory_limit_raised[id] = true;                                                         \
        }                                                                                                  \
        if (!cache_preference_set[id]) {                                                                   \
            const char * value = std::getenv("LLAMA_MMQ_Q4_CACHE_PREFERENCE");                           \
            const int mode = value != nullptr ? std::atoi(value) : 0;                                     \
            if (mode >= 1 && mode <= 3) {                                                                  \
                const cudaFuncCache preference = mode == 1 ? cudaFuncCachePreferL1 :                      \
                    (mode == 2 ? cudaFuncCachePreferShared : cudaFuncCachePreferEqual);                    \
                CUDA_CHECK(cudaFuncSetCacheConfig(kernel, preference));                                   \
            }                                                                                              \
            cache_preference_set[id] = true;                                                               \
        }                                                                                                  \
    } while (0)

#include "../mmq.cuh"

DECL_MMQ_CASE(GGML_TYPE_Q4_K);
