// This file has been autogenerated by generate_cu_files.py, do not edit manually.

// GB203 / SM120a prefill candidate for the Qwen3.8 dense FFN-down shape.
// I/J/K and arithmetic start identical to the upstream Ampere fallback; the
// macros make Blackwell-only A/B changes local to this translation unit.
#define GGML_CUDA_Q6_K_BLACKWELL_TUNING 1
#define GGML_CUDA_Q6_K_BLACKWELL_NTHREADS 256
#define GGML_CUDA_Q6_K_BLACKWELL_OCCUPANCY 1
#define GGML_CUDA_Q6_K_BLACKWELL_I 128
#define GGML_CUDA_Q6_K_BLACKWELL_J 128
#define GGML_CUDA_Q6_K_BLACKWELL_K_VRAM 256
#define GGML_CUDA_Q6_K_BLACKWELL_STREAM_K true
#define GGML_CUDA_Q6_K_BLACKWELL_PACKED_SCALE 1

// Keep this override local to the Q6_K translation unit.  GB203 has enough
// combined L1/shared capacity for the 58 KiB dynamic tile, while the kernel's
// register pressure spills a small working set to local memory.  Expose the
// CUDA cache-partition hint for clean process-level A/B tests without changing
// any values or arithmetic.  1 = PreferL1, 2 = PreferShared, 3 = PreferEqual.
#include "../common.cuh"
#include "../vecdotq.cuh"

// Q6_K weights are consumed once while the quantized activation tile is
// reused by every output-row tile. Mark the two safe 16-bit reads composing
// each packed word as streaming so cold weight lines do not displace the hot
// activation working set from GB203 L2. This changes cache replacement only.
static __device__ __forceinline__ int get_int_b2_q6_streaming(const void * x, const int & i32) {
    const uint16_t * x16 = static_cast<const uint16_t *>(x);
    int x32  = int(__ldcs(x16 + 2*i32 + 0));
    x32     |= int(__ldcs(x16 + 2*i32 + 1)) << 16;
    return x32;
}

#define get_int_b2 get_int_b2_q6_streaming
#undef CUDA_SET_SHARED_MEMORY_LIMIT
#define CUDA_SET_SHARED_MEMORY_LIMIT(kernel, nbytes)                                                       \
    do {                                                                                                   \
        static bool shared_memory_limit_raised[GGML_CUDA_MAX_DEVICES] = { false };                         \
        static bool cache_preference_set[GGML_CUDA_MAX_DEVICES] = { false };                              \
        const int id = ggml_cuda_get_device();                                                             \
        if (!shared_memory_limit_raised[id]) {                                                             \
            CUDA_CHECK(cudaFuncSetAttribute(kernel, cudaFuncAttributeMaxDynamicSharedMemorySize, nbytes)); \
            shared_memory_limit_raised[id] = true;                                                         \
        }                                                                                                  \
        if (!cache_preference_set[id]) {                                                                   \
            const char * value = std::getenv("LLAMA_MMQ_Q6_CACHE_PREFERENCE");                           \
            const int mode = value != nullptr ? std::atoi(value) : 0;                                     \
            if (mode >= 1 && mode <= 3) {                                                                  \
                const cudaFuncCache preference = mode == 1 ? cudaFuncCachePreferL1 :                      \
                    (mode == 2 ? cudaFuncCachePreferShared : cudaFuncCachePreferEqual);                    \
                CUDA_CHECK(cudaFuncSetCacheConfig(kernel, preference));                                   \
            }                                                                                              \
            cache_preference_set[id] = true;                                                               \
        }                                                                                                  \
    } while (0)

#include "../mmq.cuh"
#undef get_int_b2

DECL_MMQ_CASE(GGML_TYPE_Q6_K);
